language: php

php:
  - 5.3

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: php phpunit-4.8.phar tests/test_src/test.php

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true
  include:
    - php: 5.3
      dist: precise

notifications:
    on_success: never
    on_failure: always
